batch_size: 32
batch_size_eval: 64
n_epochs:  100
num_workers: 2
logging_freq: 200

n_classes: 0
depth: 12
image_size: 224
in_channels: 3
embed_size: 768
patch_size: 16
head: 12
hidden_size: 3072
dropout_rate: 0.1
out_dim: 1024

global_crop_scale: [0.4, 1,]
local_crop_scale: [0.05, 0.4]
n_local_crops: 8
teacher_temp: 0.04
student_temp: 0.1
center_momentum: 0.9
weight_decay: 0.4
clip_grad: 2.0
momentum_teacher: 0.9994

device: cuda:0
data_path_train: imagenette/train
data_path_val: imagenette/val
model_path: data
model_name: saved_model
labels_path: data/labels.json
logging_path: logs